baseURL = "https://rj.radiantlabs.ca/"
languageCode = "en-us"
title = "Railjack Outpost Guide"
theme = "meghna"
author = "El Heladero"
summaryLength = "15"

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.min.js"
[[params.plugins.js]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/Shuffle/5.2.3/shuffle.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/lozad.js/1.14.0/lozad.min.js"
[[params.plugins.js]]
link = "https://kit.fontawesome.com/33a0399cb5.js"

############################# Navigation ##################################
[[menu.main]]
name = "Guide"
pre = "<i class='far fa-newspaper'></i>"
URL = "guide"
weight = 1

[[menu.static]]
pre = "|"
weight = 1

[[menu.static]]
name = "Discord"
pre = "<i class='fab fa-discord'></i>"
URL = "https://discord.gg/6qKQwHR"
weight = 2

#### external / static link ####
[[menu.static]]
name = "Get Warframe"
pre = "<i class='fas fa-external-link-alt'></i>"
URL = "https://warframe.com/"
weight = 8

############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "The only guide for Warframe's Railjack you'll ever need"
author = "FriendlyFire"
# post share
post_share = true

# preloader
[params.preloader]
enable = true
preloader = "images/logo.png"

############################# social icons ##########################
[[params.social]]
icon = "fab fa-discord"
link = "https://discord.gg/6qKQwHR"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "[![Creative Commons Licence](https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png)](http://creativecommons.org/licenses/by-nc-sa/4.0/) This work is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/)."