baseURL = "https://railjack.xyz/"
languageCode = "en-us"
title = "Railjack Outpost"
theme = "meghna"
author = "El Heladero, FriendlyFire"
summaryLength = "15"
disablePathToLower = true
buildDrafts = false

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
asset = "css/vendor/bootstrap.css"
[[params.plugins.css]]
asset = "css/vendor/aos.css"
[[params.plugins.css]]
asset = "css/vendor/tooltipster.css"

# js plugins
[[params.plugins.js]]
asset = "js/vendor/jquery.js"
[[params.plugins.js]]
asset = "js/vendor/tooltipster.js"
code = "$(document).ready(() => $('.tooltipster').tooltipster());"
[[params.plugins.js]]
asset = "js/vendor/bootstrap.js"
[[params.plugins.js]]
asset = "js/vendor/fa.js"
[[params.plugins.js]]
asset = "js/vendor/aos.js"
code = "AOS.init();"

############################# Navigation ##################################
[[menu.main]]
name = "Guide"
pre = "<i class='fas fa-map-signs'></i>"
URL = "guide"
weight = 1

[[menu.main]]
name = "Reference"
pre = "<i class='fas fa-book'></i>"
URL = "reference"
weight = 1

[[menu.static]]
pre = "|"
weight = 1

[[menu.static]]
name = "Our Discord"
pre = "<i class='fab fa-discord'></i>"
URL = "https://discord.gg/6qKQwHR"
weight = 2

############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "The only guide for Warframe's Railjack that you'll ever need."
author = "FriendlyFire"
post_share = true

# preloader
[params.preloader]
enable = true
preloader = "images/logo.png"

############################# social icons ##########################
[[params.social]]
icon = "fab fa-discord"
link = "https://discord.gg/6qKQwHR"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = """[![Creative Commons Licence](https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png)](http://creativecommons.org/licenses/by-nc-sa/4.0/) This work is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/).

Digital Extremes Ltd, Warframe and the logo Warframe are registered trademarks. All rights are reserved worldwide. This site has no official link with Digital Extremes Ltd or Warframe. All artwork, screenshots, characters or other recognizable features of the intellectual property relating to these trademarks are likewise the intellectual property of Digital Extremes Ltd."""

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false